// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: AddRedSubscription.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addRedSubscription = `-- name: AddRedSubscription :exec
UPDATE users
SET is_chirpy_red = true
WHERE id = $1
`

func (q *Queries) AddRedSubscription(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, addRedSubscription, id)
	return err
}
