// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: UpdateUser.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET updated_at = $1, email = $2, hashed_password = $3
WHERE id = $4
`

type UpdateUserParams struct {
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
	ID             uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.UpdatedAt,
		arg.Email,
		arg.HashedPassword,
		arg.ID,
	)
	return err
}
