// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: UserExists.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const userExists = `-- name: UserExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE id = $1
)
`

func (q *Queries) UserExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
